#include "dark.h"

Dark::Dark(QObject *parent)
{
    Q_UNUSED(parent);

    Graphics::COLOR_WINDOW_APP = DARK_WINDOW_APP;
    Graphics::COLOR_WINDOW_WIDGET = DARK_WINDOW_WIDGET;
    Graphics::COLOR_BACKGROUND_BUTTON = DARK_BACKGROUND_BUTTON;
    Graphics::COLOR_BACKGROUND_BUTTON_DISABLED = DARK_BACKGROUND_BUTTON_DISABLED;
    Graphics::COLOR_BACKGROUND_FOCUS_IN = DARK_BACKGROUND_FOCUS_IN;
    Graphics::COLOR_COMPONENT_DISABLED = DARK_COMPONENT_DISABLED;
    Graphics::COLOR_CONTROLS = DARK_CONTROLS;
    Graphics::COLOR_DATA_AREA = DARK_DATA_AREA;
    Graphics::COLOR_DISPLAY = DARK_DISPLAY;
    Graphics::COLOR_CHART = DARK_CHART;
    Graphics::COLOR_CHART_GRIDLEG_DEFAULT = DARK_CHART_GRIDLEG_DEFAULT;
    Graphics::COLOR_CHART_GRIDLEG_LOW_CONTRAST = DARK_CHART_GRIDLEG_LOW_CONTRAST;
    Graphics::COLOR_TEXT_COMPONENT = DARK_TEXT_COMPONENT;
    Graphics::COLOR_TEXT_ALL = DARK_TEXT_ALL;
    Graphics::COLOR_TEXT_LABEL = DARK_TEXT_LABEL;
    Graphics::COLOR_HOVER = DARK_HOVER;
    Graphics::COLOR_HOVER_EXIT = DARK_HOVER_EXIT;
    Graphics::COLOR_WARNING = DARK_WARNING;
    Graphics::COLOR_ERROR = DARK_ERROR;
    Graphics::COLOR_UNINITIALIZED = DARK_UNINITIALIZED;
}

QString Dark::getThemeName(){
    return "Dark";    
}

QString Dark::getAppGlobalStyle(){
    return DARK_STYLE_GLOBAL;
}

QString Dark::getGraphicsPath(){
    return DARK_GRAPHICS_PATH;
}

QString Dark::getChannelColor(int channelIndex){
    return chanColor.at(channelIndex).name();
}
