#include "sunset.h"

Sunset::Sunset(QObject *parent)
{
    Q_UNUSED(parent);

    Graphics::COLOR_WINDOW_APP = SUNSET_BG_APP;
    Graphics::COLOR_WINDOW_WIDGET = SUNSET_BG_WIDGET;

    Graphics::COLOR_BACKGROUND_FOCUS_IN = SUNSET_FOCUS_BG;
    Graphics::COLOR_COMPONENT_DISABLED = SUNSET_DISABLED;
    Graphics::COLOR_BACKGROUND_BUTTON = SUNSET_BG_BUTTON;
    Graphics::COLOR_CONTROLS = SUNSET_TEXT_MAIN;
    Graphics::COLOR_DATA_INPUT_AREA = SUNSET_INPUT_BG;
    Graphics::COLOR_DISPLAY = SUNSET_CHART_BG;
    Graphics::COLOR_CHART = SUNSET_CHART_BG;
    Graphics::COLOR_CHART_GRIDLEG_DEFAULT = SUNSET_GRID_DEF;
    Graphics::COLOR_CHART_GRIDLEG_LOW_CONTRAST = SUNSET_GRID_LOW;
    Graphics::COLOR_TEXT_ALL = SUNSET_TEXT_MAIN;
    Graphics::COLOR_TEXT_LABEL = SUNSET_TEXT_LABEL;
    Graphics::COLOR_TEXT_COMPONENT = SUNSET_TEXT_COMP;
    Graphics::COLOR_WINDOW_CONTROL_HOVER = SUNSET_WINDOW_HOVER;
    Graphics::COLOR_WINDOW_EXIT_HOVER = SUNSET_EXIT_HOVER;
    Graphics::COLOR_WARNING = SUNSET_WARNING;
    Graphics::COLOR_ERROR = SUNSET_ERROR;
    Graphics::COLOR_RUNNING = SUNSET_RUNNING;
    Graphics::COLOR_UNUSED = SUNSET_DISABLED;

    Graphics::STYLE_PUSH_BUTTON = SUNSET_STYLE_PUSH_BUTTON;
    Graphics::STYLE_CHECK_BUTTON = SUNSET_STYLE_CHECK_BUTTON;
    Graphics::STYLE_PROGRESS_BAR = SUNSET_STYLE_PROGRESS_BAR;
    Graphics::STYLE_COMBO_BOX = SUNSET_STYLE_COMBO_BOX;
    Graphics::STYLE_CONTROL_BUTTON = SUNSET_STYLE_CONTROL_BUTTON;
    Graphics::STYLE_MODULE_BUTTON = SUNSET_STYLE_MODULE_BUTTON;
    Graphics::STYLE_HOLD_BUTTON = SUNSET_STYLE_HOLD_BUTTON;
    Graphics::STYLE_DIAL = SUNSET_STYLE_DIAL;
    Graphics::STYLE_TEXTINPUT = SUNSET_STYLE_TEXTINPUT;
    Graphics::STYLE_DOCK_WIDGET = SUNSET_STYLE_MODULE_DOCK_WIDGET;
    Graphics::STYLE_DOCK_WINDOW = SUNSET_STYLE_OBJECT;

    Graphics::STYLE_CUSTOM_DIALS_USED = SUNSET_STYLE_USE_CUSTOM_DIALS;
    Graphics::STYLE_TRANSPARENCY_USED = SUNSET_STYLE_USE_TRANSPARENCY;

    QString accent = QString(SUNSET_PINK).remove("#");
    Graphics::STYLE_GLOBAL = QString(SUNSET_STYLE_GLOBAL).arg(accent);
}

QString Sunset::getAppGlobalStyle(){
    return Graphics::STYLE_GLOBAL;
}

QString Sunset::getGraphicsPath(){
    return SUNSET_GRAPHICS_PATH;
}

QString Sunset::getChannelColor(int channelIndex){
    return chanColor.at(channelIndex).name();
}
