#ifndef PATTERNGENERATORDEFS_H
#define PATTERNGENERATORDEFS_H

#include <qtypeinfo.h>

#define PATTERNS_NUM  8
#define MAX_PATT_CHANNELS_NUM 8

#define PATT_RANGE_CHAN1_LOG1 24
#define PATT_RANGE_CHAN1_LOG0 22

#define PATT_DEFAULT_GEN_FREQ 18000000
#define PATT_DEFAULT_DATA_LENGTH 8

enum class ModeRW { RAED = 0, WRITE };

#endif // PATTERNGENERATORDEFS_H
