#ifndef SYNCPWMDEFS_H
#define SYNCPWMDEFS_H

#include <QtGlobal>

#endif // SYNCPWMDEFS_H

#define CHANNELS_NUM 4
/* Chart preview signals */
#define QCOLOR_CHAN1  QCOLOR_BLUE
#define QCOLOR_CHAN2  QCOLOR_GREEN
#define QCOLOR_CHAN3  QCOLOR_ORANGE
#define QCOLOR_CHAN4  QCOLOR_PURPLE
/* Components */
#define COLOR_CHAN1  COLOR_BLUE
#define COLOR_CHAN2  COLOR_GREEN
#define COLOR_CHAN3  COLOR_ORANGE
#define COLOR_CHAN4  COLOR_PURPLE

#define PI_HALF 90
#define DEFAULT_FREQUENCY 1000
#define DEFAULT_DC     25

#define RANGE_CHAN1_LOG1 12
#define RANGE_CHAN1_LOG0 10

#define DUTY_PRECISION     100
#define PHASE_PRECISION    100
#define FREQ_PRECISION     100

#define MAX_PAINT_PERIODS  300
