#ifndef SYNCPWMDEFS_H
#define SYNCPWMDEFS_H

#include <QtGlobal>

#endif // SYNCPWMDEFS_H

#define CHANNELS_NUM 4
#define PI_HALF 90

#define RANGE_CHAN1_LOG1 12
#define RANGE_CHAN1_LOG0 10
#define RANGE_CHAN2_LOG1 9
#define RANGE_CHAN2_LOG0 7
#define RANGE_CHAN3_LOG1 6
#define RANGE_CHAN3_LOG0 4
#define RANGE_CHAN4_LOG1 3
#define RANGE_CHAN4_LOG0 1

#define DUTY_PRECISION     100
#define PHASE_PRECISION    100
#define FREQ_PRECISION     100

#define CHANB1 0x1
#define CHANB2 0x2
#define CHANB3 0x4
#define CHANB4 0x8
#define CHANB_MASK CHANB1|CHANB2|CHANB3|CHANB4
